title: Welcome to Timofonic's Programming Adventure!
description: **NOTICE:** This site is in very early WIP status. Changes will be made when possible.
show_downloads: false
theme: jekyll-theme-hacker
